name: KBO 경기 알림

on:
  schedule:
    # KST 화~일 오전 8시
    - cron: "0 23 * * 1-6"
    # KST 화~일 오후 9시
    - cron: "0 12 * * 2-7"
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies for Selenium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver chromium

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install requests selenium pandas

      - name: Run KBO Crawler
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python kbo-crawl.py
